"""FAQ answer templates for Banking77 intent labels."""

FAQ_RESPONSES = {
    "Refund_not_showing_up": "Refunds can take several business days to appear, depending on the merchant and payment network. If the merchant confirmed the refund but it is still missing after the expected delay, check the original transaction and contact support with the refund proof.",
    "activate_my_card": "You can activate your card from the app by opening the card section and choosing the activation option. If you received a physical card, make sure you enter the requested card details correctly.",
    "age_limit": "Bank accounts and cards usually require a minimum age defined by the provider and local regulation. If you are below the required age, you may need a parent or guardian solution.",
    "apple_pay_or_google_pay": "If your card is eligible, you can add it to Apple Pay or Google Pay from your phone wallet or from the banking app. If it fails, check that your card is active and that your device supports mobile payments.",
    "atm_support": "You can withdraw cash from supported ATMs that accept your card network. Before withdrawing, check fees, limits, and whether the ATM supports your card type.",
    "automatic_top_up": "Automatic top-up lets your account add money when your balance goes below a chosen amount. You can enable, edit, or disable it from the top-up settings in the app.",
    "balance_not_updated_after_bank_transfer": "Bank transfers can take time to update your balance. Check the transfer date, sender details, and reference. If the expected processing time has passed, contact support with the transfer receipt.",
    "balance_not_updated_after_cheque_or_cash_deposit": "Cash or cheque deposits may not update instantly. Processing depends on the deposit method and banking partner. Keep the deposit receipt until the balance is updated.",
    "beneficiary_not_allowed": "A beneficiary may be refused if the details are invalid, unsupported, or blocked for security reasons. Check the recipient name, account number, country, and currency before trying again.",
    "cancel_transfer": "If the transfer is still pending, you may be able to cancel it from the transfer details. If it has already been processed, cancellation is usually not guaranteed and you should contact support quickly.",
    "card_about_to_expire": "If your card is about to expire, a replacement card is usually issued automatically or can be ordered from the app. Check your delivery address before requesting it.",
    "card_acceptance": "Card acceptance depends on the merchant, country, card network, and transaction type. If a merchant refuses the card, try another payment method and check whether your card is active.",
    "card_arrival": "Card delivery can take several working days depending on your location. If the estimated delivery date has passed, check your address and contact support to request help or a replacement.",
    "card_delivery_estimate": "The delivery estimate depends on the card type and destination country. You can usually see the estimated arrival date in the card section of the app.",
    "card_linking": "To link a card, enter the card details in the app and complete any verification step. If linking fails, check that the card is active and supported.",
    "card_not_working": "If your card is not working, check that it is active, not frozen, has enough balance, and is not blocked by limits. If the issue continues, try another terminal or contact support.",
    "card_payment_fee_charged": "Some card payments can include fees depending on currency, merchant type, or location. Check the transaction details to see whether a fee was applied.",
    "card_payment_not_recognised": "If you do not recognize a card payment, freeze your card immediately and review the transaction details. If it still looks suspicious, report it to support as soon as possible.",
    "card_payment_wrong_exchange_rate": "Exchange rates can change during processing and may include network conversion rules. Compare the transaction date, currency, and final settlement amount.",
    "card_swallowed": "If an ATM swallowed your card, freeze it in the app immediately. Contact the ATM provider or your bank support and request a replacement card if needed.",
    "cash_withdrawal_charge": "Cash withdrawals may include ATM, network, or currency conversion fees. Check the withdrawal details and your plan limits before making another withdrawal.",
    "cash_withdrawal_not_recognised": "If you do not recognize a cash withdrawal, freeze your card and contact support immediately. Provide the date, amount, ATM location, and transaction reference.",
    "change_pin": "You can usually change your card PIN from the app or at a supported ATM. Choose a PIN that is easy for you to remember but hard for others to guess.",
    "compromised_card": "If you think your card details are compromised, freeze or block the card immediately from the app. Then report the issue to support and request a replacement card.",
    "contactless_not_working": "If contactless payments are not working, try chip and PIN first. Contactless may need an initial chip transaction, may be disabled, or may have reached a security limit.",
    "country_support": "Availability depends on the country and local regulation. Check the supported countries list before opening an account or using services abroad.",
    "declined_card_payment": "A card payment can be declined because of insufficient balance, limits, security checks, merchant restrictions, or an inactive card. Check the app for transaction details and try again.",
    "declined_cash_withdrawal": "A cash withdrawal may be declined due to insufficient balance, ATM limits, card limits, or unsupported ATM network. Try a smaller amount or another ATM.",
    "declined_transfer": "A transfer can be declined if the recipient details are wrong, the currency is unsupported, limits are exceeded, or security checks fail. Review the details and try again.",
    "direct_debit_payment_not_recognised": "If you do not recognize a direct debit, review the merchant name and mandate. If it is unauthorized, contact support and consider cancelling the mandate.",
    "disposable_card_limits": "Disposable virtual cards may have limits on amount, usage, or merchant type. Check the app for the exact limit before using the card.",
    "edit_personal_details": "You can update many personal details from your profile settings. Some changes, such as legal name or identity information, may require document verification.",
    "exchange_charge": "Currency exchange can include a fee depending on the amount, currency, day, and account plan. Check the exchange preview before confirming.",
    "exchange_rate": "The exchange rate is based on the rate available at the time of conversion. Rates may change before the transaction is fully settled.",
    "exchange_via_app": "To exchange money in the app, choose the currencies, enter the amount, review the rate and fees, then confirm the exchange.",
    "extra_charge_on_statement": "An extra charge may be a fee, currency conversion adjustment, merchant pre-authorization, or delayed settlement. Check the transaction details and merchant name.",
    "failed_transfer": "If a transfer failed, the money is usually returned automatically. Check the recipient details, currency, and limits before trying again.",
    "fiat_currency_support": "Supported fiat currencies depend on the provider and region. Check the currency list in the app before sending, receiving, or exchanging money.",
    "get_disposable_virtual_card": "You can create a disposable virtual card from the card section if your account supports it. It is useful for safer online payments because details refresh after use.",
    "get_physical_card": "You can order a physical card from the card section of the app. Confirm your delivery address and review any delivery fee before ordering.",
    "getting_spare_card": "A spare card can be ordered from the app if supported by your plan. Check card fees, delivery time, and limits before confirming.",
    "getting_virtual_card": "You can create a virtual card in the app and use it for online payments. It is available faster than a physical card and can often be frozen separately.",
    "lost_or_stolen_card": "If your card is lost or stolen, freeze it immediately in the app to stop new payments. Then report it as lost or stolen and order a replacement card.",
    "lost_or_stolen_phone": "If your phone is lost or stolen, secure your account immediately. Use another device to change your passcode, remove mobile wallet access, and contact support.",
    "order_physical_card": "To order a physical card, go to the card section, choose the physical card option, confirm your address, and submit the order.",
    "passcode_forgotten": "If you forgot your passcode, use the account recovery option in the app. You may need to verify your identity before setting a new passcode.",
    "pending_card_payment": "A pending card payment means the merchant has reserved the amount but it has not fully settled. It usually updates automatically or is released if the merchant does not complete it.",
    "pending_cash_withdrawal": "A pending cash withdrawal means the ATM transaction is still being processed. If you did not receive the cash, keep the receipt and contact support if it does not reverse.",
    "pending_top_up": "A pending top-up means the payment is still being processed. Check the payment method and wait for the expected processing time before trying again.",
    "pending_transfer": "A pending transfer means it has been submitted but not completed yet. Processing time depends on the transfer type, bank, country, and currency.",
    "pin_blocked": "If your PIN is blocked, you may need to unblock it in the app or at a supported ATM. If that does not work, contact support before trying too many times.",
    "receiving_money": "To receive money, share the correct account details for the currency and transfer type. Make sure the sender uses the exact beneficiary name and reference if required.",
    "request_refund": "To request a refund, contact the merchant first because they usually need to initiate it. If the merchant refuses or does not respond, support may help with a dispute.",
    "reverted_card_payment?": "A reverted card payment means the transaction was returned or cancelled. The amount should go back to your balance after processing.",
    "supported_cards_and_currencies": "Supported cards and currencies depend on the service, country, and payment network. Check the app before adding a card or making a payment.",
    "terminate_account": "To close your account, withdraw or transfer remaining funds, resolve pending transactions, then contact support or use the account closure option if available.",
    "top_up_by_bank_transfer_charge": "Top-up by bank transfer is often free, but charges may depend on the sending bank, currency, and transfer type. Check the transfer details before sending.",
    "top_up_by_card_charge": "Card top-ups may include a fee depending on the card type, country, or currency. Review the fee shown before confirming the top-up.",
    "top_up_by_cash_or_cheque": "Cash or cheque top-ups depend on supported deposit partners. Processing can take longer than card or bank transfer top-ups.",
    "top_up_failed": "A top-up can fail because of card issuer refusal, insufficient funds, limits, incorrect details, or security checks. Try another method if the issue continues.",
    "top_up_limits": "Top-up limits depend on your account, verification level, payment method, and currency. Check the limits section in the app.",
    "top_up_reverted": "A reverted top-up means the top-up was cancelled or returned to the original payment method. It may take several business days to appear there.",
    "topping_up_by_card": "To top up by card, open the top-up section, choose card, enter the amount, select or add a card, then confirm the payment.",
    "transaction_charged_twice": "If a transaction was charged twice, check whether one charge is still pending. If both charges settle, contact support with the transaction details.",
    "transfer_fee_charged": "Transfer fees depend on currency, destination country, transfer method, and account plan. The fee should be shown before confirmation.",
    "transfer_into_account": "To transfer money into your account, use the account details shown in the app. Make sure the sender uses the correct currency and reference.",
    "transfer_not_received_by_recipient": "If the recipient has not received the transfer, check the transfer status, recipient details, and expected delivery time. Contact support with the transfer receipt if delayed.",
    "transfer_timing": "Transfer timing depends on the currency, destination country, recipient bank, and transfer method. Some transfers are instant, while others take several business days.",
    "unable_to_verify_identity": "If identity verification failed, check that your document is valid, readable, not expired, and matches your account details. Try again in good lighting.",
    "verify_my_identity": "To verify your identity, follow the app instructions and upload the requested document or selfie. Make sure all details are clear and match your account.",
    "verify_source_of_funds": "Source of funds verification may require documents such as payslips, bank statements, invoices, or sale agreements. Upload clear documents that explain where the money came from.",
    "verify_top_up": "A top-up may need verification for security reasons. Follow the app instructions and confirm the payment method or provide the requested proof.",
    "virtual_card_not_working": "If your virtual card is not working, check that it is active, not frozen, has enough balance, and is accepted by the merchant.",
    "visa_or_mastercard": "The card network can be Visa or Mastercard depending on the card issued in your region. You can see the network logo on the card details.",
    "why_verify_identity": "Identity verification is required to protect your account, prevent fraud, and comply with financial regulations.",
    "wrong_amount_of_cash_received": "If the ATM gave the wrong cash amount, keep the receipt and note the ATM location and time. Contact support so the withdrawal can be investigated.",
    "wrong_exchange_rate_for_cash_withdrawal": "Cash withdrawal exchange rates depend on ATM, card network, and currency conversion timing. Check whether the ATM applied its own conversion rate.",
}


def get_faq_response(label: str | None) -> str:
    if not label:
        return "I could not identify the banking topic clearly. Please add more details about the card, transfer, payment, top-up, or verification issue."
    return FAQ_RESPONSES.get(
        label,
        "I detected the banking topic, but I do not have a detailed FAQ answer for this category yet. Please provide more details so support can handle it correctly.",
    )
